### ISSUE TITLE
error builEnvironment key "cypress/globals" is unknown

### ISSUE THREAD

**Issue by teddy-f-47** [haanh764/surveyapp#41]
After merging PR #39 , I am unable to run `docker-compose build` because I keep getting the following error:
<img width="960" alt="error1" src="https://user-images.githubusercontent.com/64476430/174078137-cfec8c10-c58a-471a-a97a-fa930a6802c7.png">

```
 => ERROR [build-stage 6/7] RUN yarn run lint --fix                                                                                                                    2.2s
------
 > [build-stage 6/7] RUN yarn run lint --fix:
#12 0.726 yarn run v1.22.19
#12 0.777 $ vue-cli-service lint --fix
#12 2.109  ERROR  Error: tests/e2e/.eslintrc.js:56:e8a8c4a3dcf79ba2b087951b2a89f7c5bee826da1c5324e65a4bdebeac1bce9a                                                    0.0s
#12 2.109         d builEnvironment key "cypress/globals" is unknown                                                                                                   0.0s
#12 2.109         g context: 2.77kB                                                                                                                                    0.0s
#12 2.109 Error: tests/e2e/.eslintrc.js:                                                                                                                               0.0s
#12 2.109 ADD . Environment key "cypress/globals" is unknown                                                                                                           0.0s
#12 2.109 RUN pip install -r requirements.txt                                                                                                                         79.9s
#12 2.109     at /app/node_modules/@eslint/eslintrc/lib/shared/config-validator.js:175:23
#12 2.109     at Array.forEach (<anonymous>)I, pytz, flask-blueprint, blinker, aniso8601, zipp, Werkzeug, tenacity, six
#12 2.109     at ConfigValidator.validateEnvironment (/app/node_modules/@eslint/eslintrc/lib/shared/config-validator.js:169:34)
#12 2.109     at ConfigValidator.validateConfigArray (/app/node_modules/@eslint/eslintrc/lib/shared/config-validator.js:319:18)
#12 2.109     at CascadingConfigArrayFactory._finalizeConfigArray (/app/node_modules/@eslint/eslintrc/lib/cascading-config-array-factory.js:493:23)
#12 2.109     at CascadingConfigArrayFactory.getConfigArrayForFile (/app/node_modules/@eslint/eslintrc/lib/cascading-config-array-factory.js:299:21)
#12 2.109     at CLIEngine.isPathIgnored (/app/node_modules/eslint/lib/cli-engine/cli-engine.js:973:18)
#12 2.109     at ESLint.isPathIgnored (/app/node_modules/eslint/lib/eslint/eslint.js:688:26)
#12 2.109     at /app/node_modules/@vue/cli-plugin-eslint/lint.js:103:24
#12 2.109     at Array.map (<anonymous>)ackages: uWSGI, flask-blueprint, Flask-Mail, blinker
#12 2.128 error Command failed with exit code 1.started
#12 2.128 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
------ # Collecting zipp>=0.5
executor failed running [/bin/sh -c yarn run lint --fix]: exit code: 1
ERROR: Service 'ui' failed to build : Build failedWSGI, flask-blueprint, Flask-Mail, blinker
 => => #   Building wheel for uWSGI (setup.py): started
```

Anybody know what's the culprit and how to fix it? I have tried deleting the container and building from scratch, didn't help.

**Comment by teddy-f-47** [comment]
Maybe @artikandri can help? 😓

**Comment by teddy-f-47** [comment]
I think I have found a solution by adding `"eslint-plugin-cypress": "^2.0.1",` in the package.json. I will include it in my future PR.

**Comment by artikandri** [comment]
Sorry, I haven't checked my emails and messages. Thank you for solving
this. I have added the package in my branch but haven't made the PR 😓

czw., 16 cze 2022, 15:34 użytkownik Teddy Ferdinan ***@***.***>
napisał:
